# NAME: docker-compose.yml
# AUTH: Ryan McCartney <ryan@mccartney.info>
# DATE: 08/01/2023
# DESC: FFmpeg compiled with configurable options link BMD Decklink or Newtec NDI

version: "3.8"

services:
    ffmpeg:
        container_name: ffmpeg
        build:
            context: "."
            args:
                DECKLINK_SUPPORT: "true"
                DECLINK_SDK_URL: "https://sw.blackmagicdesign.com/DeckLink/v12.4.1/Blackmagic_DeckLink_SDK_12.4.1.zip?Key-Pair-Id=APKAJTKA3ZJMJRQITVEA&Signature=LxNgk8c6Qq7rTfyH8Rb/1szyO3IMc1k3I9WwiBIU2AAZizsBJuqysqFXDfCf8tS5cLohYcsQRJGa5QyDLPucvrLLUg0WGHgRgAW589xOgOV012czmsHmCL6fvYwVKwq2d68Da2wLIjMgqf3vIKwMwEzaC7KSMQqLpsIBpKcOAoBVn9R1JEixLW0fT+E/KVYVzADRguX9B2+ErUnYBT/7TpO4itYW8MurhNPmBxoSBHcTtzPk/HnMQOrbDgoseqzqXht8dKMMWPp2RAUfbMwHRlZ5K2qlVj/Iv3bm0FZH6uFbypVp73xYKPy9dtEwesK2HYokWnPuNpiUOTKR5dgcIQ==&Expires=1674324162"
                DECKLINK_DRIVER_URL: "https://sw.blackmagicdesign.com/DesktopVideo/v12.4.1/Blackmagic_Desktop_Video_Linux_12.4.1.tar.gz?Key-Pair-Id=APKAJTKA3ZJMJRQITVEA&Signature=TR/CscFoA7LD+NgmASj/TNvfXDXyx+oRvJMRql1UIXtubE0sC5JJJF8/8q7wujw9QYxAd4aAQX08oHIYYREH0fQ/GyjAg03anJbakj+LhMqB2JjKIThyJOr4J+6/xXv6agt0txRQNgQgOPDV+F5UPc+yXP4iExyQVOh6E5dHVjt3sIz6qz6hv36NQtEgxlL8NkM2ZpLVnRK/5t7EoJw3dZuz3TkpZxXgRdV8Of0YtE9a3cVWRn4T3uZDKKEr0XEVq4lJzp7DJ8xVXjSGIYemS3aW3Zp7HnnMq4TvpQ6WresYbk41C4Ie+rXqI7pOK4MBoXvVZJbw3LSL4CRM7w8UfQ==&Expires=1674324133"
                NDI_SUPPORT: "false"
                NDI_SDK_URL: "https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz"
        restart: always
        volumes:
            - ./:/home/node/app
        devices:
            - /dev/blackmagic/io0:/dev/blackmagic/io0
        environment:
            NODE_ENV: "development"
            PORT: 80
        ports:
            - 3000:80
            - 5004:5004
