# NAME: docker-compose.yml
# AUTH: Ryan McCartney <ryan@mccartney.info>
# DATE: 08/01/2023
# DESC: FFmpeg compiled with configurable options link BMD Decklink or Newtec NDI

version: "3.8"

services:
    ffmpeg:
        container_name: ffmpeg
        build:
            context: "."
            args:
                DECKLINK_SUPPORT: "true"
                DECLINK_SDK_URL: "https://sw.blackmagicdesign.com/DeckLink/v12.5/Blackmagic_DeckLink_SDK_12.5.zip?Key-Pair-Id=APKAJTKA3ZJMJRQITVEA&Signature=MnzNr1B56klWNEfkuBdsrs+hsNTA7JZBY9wwejbAMiGdvphubvGixfURihJp6kcqk3sav5UUpUmvnAHEEAp3nPqU3nxIIEJTbVzGNSAt0GaA6+8b2WHvJ//7g4x/8ZQUgA/htniWekayjJFjwJyBnk2ApdVFPkW9GizTYhLqNkN1o22rJfiAHEHXxIL8O+908oc7Ied3Qs2ZT8CTmDA0euE5TM9gNRTneJ96wkuj8l8qA2UcAVqif0ZEAmDEg5uSxrroa3DqOb8NShSGzsATozEykuC6dRU422ZidnO8Hqy4wBCUMY/iSBMmKvSTNHCl1w0S2imxNsrfr8eeaocFJQ==&Expires=1688337534"
                DECKLINK_DRIVER_URL: "https://sw.blackmagicdesign.com/DesktopVideo/v12.5-1/Blackmagic_Desktop_Video_Linux_12.5.tar.gz?Key-Pair-Id=APKAJTKA3ZJMJRQITVEA&Signature=m5TKzaYoB26Mt0qT8QV8JDCOFkLzeX3tT9GR7j/zz/EgybDbXSUPx/V9Q/IpIA6YI5LWP+3huhcANkFZsxensMWjCLK9lZYoed/fC2rxKB/eTJy+Jd6JWRlFXw0hQPH1qVXDxZXC809LQkm0ALT4sBRZQFX+mzaDqyM/5Cd3DMxdjuNYjQSmMQXXumO+BxxAr4V8xQJWc3mjaWTepRtLvuvvRghCAzGyh8VLS2YY69UMneyiQcQvGZLc4Og8qXtblNIbYpvadoAobeBHFrQRoM4FGdF3iqypsfJHE2yAGQ32Yal18XP0O0qZGv/IlnF892VT1FLldAml0pGf+sVR0A==&Expires=1688337504"
                DECKLINK_DRIVER_VERSION: "12.5"
                NDI_SUPPORT: "false"
                NDI_SDK_URL: "https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz"
        restart: always
        volumes:
            - ./:/home/node/app
        devices:
            - /dev/blackmagic/io0:/dev/blackmagic/io0
        environment:
            NODE_ENV: "development"
            PORT: 80
        ports:
            - 3000:80
            - 5004:5004
