# NAME: docker-compose.yml
# AUTH: Ryan McCartney <ryan@mccartney.info>
# DATE: 08/01/2023
# DESC: FFmpeg compiled with configurable options link BMD Decklink or Newtec NDI

version: "3.8"

services:
    ffmpeg:
        container_name: ffmpeg
        build:
            context: "."
            args:
                DECKLINK_SUPPORT: "true"
                DECLINK_SDK_URL: "https://sw.blackmagicdesign.com/DeckLink/v12.4.1/Blackmagic_DeckLink_SDK_12.4.1.zip?Key-Pair-Id=APKAJTKA3ZJMJRQITVEA&Signature=MxoRQCMnu9Ag46rAfF7TbLiYNiFXb8D8PmRi3QDZ+M8FZVfTe08DOk4xGQHcpfeMnpKs2kUs6K8Sd0wwLYmw8sUvBY1iBWU40slDYwi0PRp6O2wyJfWvd8yJpV4/oepnovGpJoboqnaWQCIUwdm2e5F8VpDP8ambdchTyTHCLWbDUgK8kXTpLLFN7kDE3Et4dbsDhjosWcr7Tat4MBWpYSLF7jkMO63eTclB/v0Bx2jI/QPzzK2eIWOftHw0nVeooduueQfggrSWnakfykMuOUKouxp+R84p+zVYhJ2ONht+Wx3k1FNs89QIuBD6p7WUYskqKah8pRcOkv25sThbDg==&Expires=1689078171"
                DECKLINK_DRIVER_URL: "https://sw.blackmagicdesign.com/DesktopVideo/v12.4.1/Blackmagic_Desktop_Video_Linux_12.4.1.tar.gz?Key-Pair-Id=APKAJTKA3ZJMJRQITVEA&Signature=PVEpuAZiRv0qCD6P4Ulv8/0XEsFftbYhJZMMF3tY1S+afb+RxBy3SW/JhXzgXSP3oXBd1JNVyTPxYrpHpa198yYl8ZrZsw862MCHzkBKwupqKv0o9bpucb7padXUFvSSxOoLa4piw15jobD9BjFPDaaDr7cZHd7Mi9ci9hhGnZ68qB6/d1rP+AUV1rMpsbsr5lG7zYZNklnCOQBPTmyZmuGm+SEp6RmOks6Bp9dBAQx+R4Cde1ym4K7q5gsVKk9QvQguOzVl/EZ7tWxMWanPlajIqFlSv7ETHQRacdy74tBJVMT3oa0tSPCtGp/tUrBudlRdRc7EA7sdRDsfjwmHXQ==&Expires=1689078142"
                DECKLINK_DRIVER_VERSION: "12.4.1"
                NDI_SUPPORT: "true"
                NDI_SDK_URL: "https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz"
        restart: always
        volumes:
            - ./:/home/node/app
        devices:
            - /dev/blackmagic/dv0:/dev/blackmagic/dv0
        environment:
            NODE_ENV: "development"
            PORT: 80
            HOST: "172.26.182.69"
        ports:
            - 3000:80
            - 5004:5004
