services:
  ffmpeg-audio-api:
    build: .
    ports:
      - "9000:3000"
    volumes:
      - ./cookies:/app/cookies
    environment:
      - COOKIES_UPLOAD_SECRET=${COOKIES_UPLOAD_SECRET:-}
      - YOUTUBE_COOKIES_PATH=${YOUTUBE_COOKIES_PATH:-}
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
