# NAME: docker-compose.yml
# AUTH: Ryan McCartney <ryan@mccartney.info>
# DATE: 08/01/2023
# DESC: FFmpeg compiled with configurable options link BMD Decklink or Newtec NDI

version: "3.8"

services:
    ffmpeg:
        container_name: ffmpeg
        network_mode: "host"
        build:
            context: "."
            args:
                DECKLINK_SUPPORT: "true"
                DECLINK_SDK_URL: "https://swr.cloud.blackmagicdesign.com/DeckLink/v12.4.1/Blackmagic_DeckLink_SDK_12.4.1.zip?verify=1697909201-45BDvNhH%2Fz5NbY6ai6b6cMKMIuFPZk3DUylMOXgCfvM%3D"
                DECKLINK_DRIVER_URL: "https://swr.cloud.blackmagicdesign.com/DesktopVideo/v12.4.1/Blackmagic_Desktop_Video_Linux_12.4.1.tar.gz?verify=1697908812-1f7rrMkhP0aqofYc4hhVOuLdCJhqpWd2B2Dl8%2Bten0k%3D"
                DECKLINK_DRIVER_VERSION: "12.4.1"
                NDI_SUPPORT: "false"
                NDI_SDK_URL: "https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz"
        restart: always
        volumes:
            - ./:/home/node/app
        devices:
             - /dev/blackmagic/io0:/dev/blackmagic/io0
        environment:
            NODE_ENV: "development"
            PORT: 80
            HOST: "172.26.108.42"
            WEB_GUI: "true"
        ports:
            - 80:80
            - 5004:5004
