# NAME: docker-compose.yml
# AUTH: Ryan McCartney <ryan@mccartney.info>
# DATE: 08/01/2023
# DESC: FFmpeg compiled with configurable options link BMD Decklink or Newtec NDI

version: "3.8"

services:
    ffmpeg:
        container_name: ffmpeg
        # network_mode: "host" #Change this as required
        build:
            context: "."
            args:
                DECKLINK_SUPPORT: "false"
                DECKLINK_SDK_URL: "https://swr.cloud.blackmagicdesign.com/DeckLink/v12.4.1/Blackmagic_DeckLink_SDK_12.4.1.zip?verify="
                DECKLINK_DRIVER_URL: "https://swr.cloud.blackmagicdesign.com/DesktopVideo/v12.4.1/Blackmagic_Desktop_Video_Linux_12.4.1.tar.gz?verify="
                DECKLINK_DRIVER_VERSION: "12.4.1"
                NDI_SUPPORT: "false"
                NDI_SDK_URL: "https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz"
                NON_FREE: "true"
        restart: always
        volumes:
            - ./:/home/node/app
        #devices:
        #    - /dev/blackmagic/io0:/dev/blackmagic/io0
        environment:
            NODE_ENV: "development"
            PORT: 80
            HOST: "localhost"
            WEB_GUI: "true"
            AUTH_KEY: "averysecretkey"
            AUTH_USER: admin
            AUTH_PASSWORD: admin
        ports:
            - 80:80
